<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SignalRThroughputBench.Contracts\SignalRThroughputBench.Contracts.csproj" />
    <ProjectReference Include="..\..\src\SignalRThroughputBench.Runner\SignalRThroughputBench.Runner.csproj" />
    <ProjectReference Include="..\..\src\SignalRThroughputBench.Server\SignalRThroughputBench.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
