<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\SignalRThroughputBench.Contracts\SignalRThroughputBench.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" />
  </ItemGroup>
</Project>
